### ISSUE TITLE
find_files actually returns everything, not just files. So it's not actually like find type -f.

### ISSUE THREAD

**Issue by beantaxi** [ewiger/findtools#3]
It looks like a very easy fix. Just go to the find_files function, and get rid of `dirs + files` so you only return files. You could then add a `find_dirs` function that worked the same, but on dirs instead. Then you'd be on your way to emulating Gnu find.

As it stands, the single example on your README.md doesn't actually do what it says, so I couldn't even star this repo.

I'd be happy to make the change above but this project doesn't appear active. But I figured I could at least raise an isssue.

**Comment by ewiger** [comment]
Indeed this lib was quite outdated, so thanks for bringing this to my attention. I quickly updated the syntax. Tests do work for me now at 2.7 (to be deprecated) and 3.8.

```
(py38) ➜  python pip install findtools==1.1.0
Collecting findtools==1.1.0
  Downloading findtools-1.1.0.tar.gz (4.5 kB)
Building wheels for collected packages: findtools
  Building wheel for findtools (setup.py) ... done
  Created wheel for findtools: filename=findtools-1.1.0-py3-none-any.whl size=4597 sha256=e08a0e38495e39b08a60f9a90ec9ef9837ff80c646d948e9484e3a3d596bdecc
  Stored in directory: /root/.cache/pip/wheels/d5/d3/ff/a5bdbe917c403abe51f4307a17041ff185ef71fc85193892b6
Successfully built findtools
Installing collected packages: findtools
  Attempting uninstall: findtools
    Found existing installation: findtools 1.0.3
    Uninstalling findtools-1.0.3:
      Successfully uninstalled findtools-1.0.3
Successfully installed findtools-1.1.0

(py38) ➜  python cat t.py
from findtools.find_files import (find_files, Match)


# Recursively find all *.sh files in **/usr/bin**
sh_files_pattern = Match(filetype='f', name='*.sh')
found_files = find_files(path='/usr/bin', match=sh_files_pattern)

for found_file in found_files:
        print(found_file)#

(py38) ➜  python python t.py
/usr/bin/gettext.sh
```

So the above works also with the sample snippet.

Regarding you use-case - it is still unclear for me why using `Match()` to be selective about files vs dirs is not working for you.

Please update the package to findtools 1.1.0 and attach your piece of code that is breaking for you.

Otherwise I will not be reluctant to close this issue in few days or so. Thanks.
```

**Comment by ewiger** [comment]
IMO the callback filter with `Match(filetype='d')`  should do the trick for filtering folders - see https://github.com/ewiger/findtools/blob/master/src/findtools/find_files.py#L15

If this does not work for you @beantaxi, please open a new ticket with a code example that does not work.

**Comment by beantaxi** [comment]
I confirmed this is looking good. And I wasn't aware / didn't understand the use of `Match` when I first looked your code; I think from the function name `find_files` I assumed its job was to only find files, and `Match` was only there to specify a filename or wildcard. The current example makes that clear.

Thanks for having a look! I like the idea of the lib btw; I love GNU `find`.

**Comment by ewiger** [comment]
you are welcome
